version: '3.8'
services:
    api:
        build: .
        ports:
            - '${PORT}:8080'
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        depends_on:
            - db

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data

    client:
        build: ../money-client/
        ports:
            - '${CLIENT_PORT}:3000'
        environment:
            MODE: ${MODE}
            API_URL_PRODUCTION: ${API_URL_PRODUCTION}
            API_URL_DEVELOPMENT: ${API_URL_DEVELOPMENT}
            API_ENDPOINT: ${API_ENDPOINT}
            CLIENT_PORT: ${CLIENT_PORT}
        depends_on:
            - api

volumes:
    db_data:
