networks:
    db-network:
        driver: bridge
    money-network:
        driver: bridge

services:
    postgres:
        container_name: postgres
        image: postgres:16.2-alpine3.19
        restart: always
        shm_size: 128mb
        volumes:
            - 'users-postgres:/var/lib/postgresql/data'
        networks:
            - db-network
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        ports:
            - ${DB_PORT}:5432

    backend:
        container_name: money-backend
        build:
            context: './'
        restart: always
        # command: ./docker-entrypoint.sh
        environment:
            - POSTGRES_USER
            - DB_HOST
            - POSTGRES_DB
            - POSTGRES_PASSWORD
            - DB_PORT
            - JWT_SECRET
            - PORT
            - DB_LOGGING
        networks:
            - money-network
            - db-network
        ports:
            - 3000:3000
        depends_on:
            - postgres

    frontend:
        container_name: money-frontend
        build:
            context: '../money-client/'
        restart: always
        networks:
            - money-network
        environment:
            - MODE
            - API_URL_PRODUCTION
            - API_URL_DEVELOPMENT
            - API_ENDPOINT
            - API_PORT
            - PORT=3001
        ports:
            - 3001:3001
        depends_on:
            - backend

volumes:
    users-postgres:
