networks:
  db-network:
    driver: bridge
  money-network:
    driver: bridge

volumes:
  users-postgres:

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: money-server
    restart: always
    shm_size: 128mb
    volumes:
      - "users-postgres:/var/lib/postgresql/data"
    networks:
      - db-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - ${DB_PORT}:5432

  backend:
    build:
        context: "./"
    container_name: money-backend
    restart: always
    command: ./docker-entrypoint.sh
    networks:
      - money-network
      - db-network
    environment:
      - JWT_SECRET
      - NODE_ENV
    ports:
      - 8080:8080
      - 5555:5555
    depends_on:
      - postgres

  frontend:
    build:
        context: "../money-client/"
    container_name: money-frontend
    restart: always
    networks:
      - money-network
    environment:
      - API_ENDPOINT
      - API_PORT
      - PORT=3001
    ports:
      - 3001:3001
    depends_on:
      - backend